### ISSUE TITLE
encounter an error in running demo.py

### ISSUE THREAD

**Issue by kaishijeng** [ruinmessi/ASFF#47]
I got maximum recursion depth error when I run the following demo.py:

python3 demo.py -i test.jpg --cfg config/yolov3_baseline.cfg -d COCO --checkpoint YOLOv3-mobile-asff.pth --asff  -s 416

/home/test/anaconda3/envs/detectron2/lib/python3.6/site-packages/torchvision-0.5.0a0+1e857d9-py3.6-linux-x86_64.egg/torchvision/io/_video_opt.py:17: UserWarning: video reader based on ffmpeg c++ ops not available
Setting Arguments.. :  Namespace(asff=True, cfg='config/yolov3_baseline.cfg', checkpoint='YOLOv3-mobile-asff.pth', dataset='COCO', half=False, img='test.jpg', rfb=False, test_size=416, use_cuda=True)
successfully loaded config file:  {'MODEL': {'TYPE': 'YOLOv3', 'BACKBONE': 'mobile'}, 'TRAIN': {'LR': 0.001, 'MOMENTUM': 0.9, 'DECAY': 0.0005, 'BURN_IN': 5, 'MAXEPOCH': 300, 'COS': True, 'SYBN': True, 'MIX': True, 'NO_MIXUP_EPOCHS': 30, 'LABAL_SMOOTH': True, 'BATCHSIZE': 5, 'IMGSIZE': 608, 'IGNORETHRE': 0.7, 'RANDRESIZE': True}, 'TEST': {'CONFTHRE': 0.01, 'NMSTHRE': 0.65, 'IMGSIZE': 608}}
For mobilenet, we currently don't support dropblock, rfb and FeatureAdaption
Training YOLOv3 with ASFF!
loading pytorch ckpt... YOLOv3-mobile-asff.pth
using cuda
Traceback (most recent call last):
  File "/home/test/anaconda3/envs/detectron2/lib/python3.6/site-packages/torchvision-0.5.0a0+1e857d9-py3.6-linux-x86_64.egg/torchvision/ops/boxes.py", line 31, in nms
  File "/home/test/anaconda3/envs/detectron2/lib/python3.6/site-packages/torchvision-0.5.0a0+1e857d9-py3.6-linux-x86_64.egg/torchvision/ops/boxes.py", line 31, in nms
  File "/home/test/anaconda3/envs/detectron2/lib/python3.6/site-packages/torchvision-0.5.0a0+1e857d9-py3.6-linux-x86_64.egg/torchvision/ops/boxes.py", line 31, in nms
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded

**Comment by ruinmessi** [comment]
@kaishijeng use config/yolov3_mobile.cfg instead. I forget to update this cfg file last night.

**Comment by huoguangdiandian** [comment]
请问 YOLOv3-mobile-asff.pth在哪里获取的
