### ISSUE TITLE
TypeError: evaluate() takes from 2 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by ys0823** [ruinmessi/ASFF#58]
I get this error when I train the model by using
 `python -m torch.distributed.launch --nproc_per_node=4 --master_port=1234 main.py --cfg config/yolov3_baseline.cfg -d VOC --distributed --ngpu 4 --checkpoint weights/darknet53_feature_mx.pth --start_epoch 0 --half --asff --rfb --dropblock --log_dir log/VOC_ASFF -s 608` to train.

it seems that the input of the eval code  is wrong:

`Original exception was:
Traceback (most recent call last):
  File "/data/tanglin/software/pycharm-2018.3.2/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/data/tanglin/software/pycharm-2018.3.2/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/data/tanglin/software/pycharm-2018.3.2/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/data/tanglin/software/pycharm-2018.3.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data/tanglin/ASFF/ASFF/main.py", line 470, in <module>
    main()
  File "/data/tanglin/ASFF/ASFF/main.py", line 365, in main
    ap50_95, ap50 = evaluator.evaluate(model, args.half,args.distributed)` 

what can I do? @ruinmessi 
THANKS

**Comment by ruinmessi** [comment]
@ys0823  It seems a bug exists on the voc evaluator. I will check this at the weekend.

**Comment by westnight** [comment]
@ruinmessi Have you figure it out? Looking forward

**Comment by KelvinHuang666** [comment]
line 365, in main ap50_95, ap50 = evaluator.evaluate(model, args.half,args.distributed)
instand of
 ap50_95, ap50 = evaluator.evaluate(model, args.half)

**Comment by xaohuicai** [comment]
多了个参数，给evaluator.evaluate（）函数添加一个参数distributed=False
