### ISSUE TITLE
out of memory at the end of epoch7

### ISSUE THREAD

**Issue by ShoufaChen** [ruinmessi/ASFF#7]
Hello, thank you for your great work.

I found an `out of memory` error at the end of epoch 7.

I use 8 2080Ti GPUs, and my training scripts is:
```
python -m torch.distributed.launch --nproc_per_node=8 --master_port=233323 main.py \
        --cfg config/yolov3_baseline.cfg -d COCO --tfboard --distributed --ngpu 8 \
        --checkpoint weights/darknet53_feature_mx.pth --start_epoch 0 --half --asff --rfb --dropblock \
        --log_dir log/COCO_ASFF -s 608
```

The error log is:
```
[Epoch 7/300][Iter 2930/2957][lr 0.001000][Loss: anchor 9.82, iou 10.44, l1 32.70, conf 27.21, cls 79.91, imgsize 544, time: 6.14]
[Epoch 7/300][Iter 2940/2957][lr 0.001000][Loss: anchor 9.65, iou 10.57, l1 32.50, conf 26.13, cls 76.35, imgsize 512, time: 6.48]
[Epoch 7/300][Iter 2950/2957][lr 0.001000][Loss: anchor 12.56, iou 13.53, l1 41.10, conf 31.59, cls 95.52, imgsize 512, time: 6.16]
Traceback (most recent call last):
  File "main.py", line 454, in <module>
    main()
  File "main.py", line 388, in main
    optimizer.backward(loss)
  File "/mnt/WXRG0353/sfchen/ASFF/utils/fp16_utils/fp16_optimizer.py", line 483, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/mnt/WXRG0353/sfchen/ASFF/utils/fp16_utils/loss_scaler.py", line 45, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/mnt/WXRG0333/sfchen/anaconda3/envs/pytorch13/lib/python3.7/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/WXRG0333/sfchen/anaconda3/envs/pytorch13/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 8.16 GiB (GPU 5; 10.73 GiB total capacity; 1.76 GiB already allocated; 8.16 GiB free; 29.42 MiB cached)
```

and the `nvidia-smi` message:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:1A:00.0 Off |                  N/A |
| 34%   55C    P2   100W / 250W |   2922MiB / 10989MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  On   | 00000000:1B:00.0 Off |                  N/A |
| 35%   58C    P2    92W / 250W |   2920MiB / 10989MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  On   | 00000000:3D:00.0 Off |                  N/A |
| 33%   52C    P2   113W / 250W |   2912MiB / 10989MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  On   | 00000000:3E:00.0 Off |                  N/A |
| 33%   51C    P2   101W / 250W |   2920MiB / 10989MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  On   | 00000000:88:00.0 Off |                  N/A |
| 32%   49C    P2    90W / 250W |   2922MiB / 10989MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  On   | 00000000:89:00.0 Off |                  N/A |
| 27%   29C    P8     4W / 250W |     11MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  On   | 00000000:B1:00.0 Off |                  N/A |
| 27%   28C    P8     1W / 250W |     11MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  On   | 00000000:B2:00.0 Off |                  N/A |
| 27%   28C    P8     1W / 250W |     11MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0    173812      C   ...hen/anaconda3/envs/pytorch13/bin/python  2911MiB |
|    1    173813      C   ...hen/anaconda3/envs/pytorch13/bin/python  2909MiB |
|    2    173814      C   ...hen/anaconda3/envs/pytorch13/bin/python  2901MiB |
|    3    173815      C   ...hen/anaconda3/envs/pytorch13/bin/python  2909MiB |
|    4    173816      C   ...hen/anaconda3/envs/pytorch13/bin/python  2911MiB |
+-----------------------------------------------------------------------------+
```

**Comment by ruinmessi** [comment]
For 2080ti, I also meet this memory issue when I set batchsize at 6. The reason is that random resizing consumes a lot of GPU memory. You may turn-off the random resizing if you don't care about the final accuracy, or set batchsize at 5 or 4, and also adjust the init lr with 0.0005.

**Comment by ShoufaChen** [comment]
Thank you for your reply.
